### ISSUE TITLE
boot2docker

### ISSUE THREAD

**Issue by mjhea0** [ActivisionGameScience/ags_conda_recipes#1]
This point is not accurate since you can use [boot2docker](http://boot2docker.io) -

"To address point (1) you can use docker (assuming you are willing to limit yourself to a modern Linux)."

**Comment by sstirlin** [comment]
boot2docker is just a stripped-down Linux VM.  Docker definitely doesn't run on Windows or Mac natively.

**Comment by mjhea0** [comment]
True. I think it's a bit misleading the way it's currently written, though. Docker doesn't run on Windows or Mac OS X natively since it needs part of the Linux kernel to function properly. But Boot2docker is def. a sound solution. You just may want to re-word it a bit. Want me to issue a PR?

Anyway, I am very interested in Conda and how it can be used in much the same way as Docker for both on-boarding new employees much faster as well as deploying. Would you be able to connect off Github to discuss? Best!

**Comment by sstirlin** [comment]
Yes, point taken.  I'll remove that comment and do some rewording to clarify that conda and docker are really solving different problems (although there is some overlap).  We use both conda, docker, and vagrant pretty heavily (together, in fact).

For sure, let's definitely connect offline.  My email address is spencerBLAHstirlingHAHAactivisionBLAHcom where BLAH=. and HAHA=@

**Comment by sstirlin** [comment]
Fixed (I hope).  It won't be the last fix for sure.  I need to add Windows and Mac instructions, but probably with a simpler environment because I've only built maybe a third of our packages in Windows.
